// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.qualicom.wscrpt.domain;

import com.qualicom.wscrpt.domain.AcctData;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AcctData_Roo_Configurable {
    
    declare @type: AcctData: @Configurable;
    
}
